### ISSUE TITLE
修改Action

### ISSUE THREAD

**Issue by Ran-Xing** [wekingchen/Actions-SFT1200-OpenWrt#4]
```diff
--  workflow_dispatch:
--    inputs:
--      ssh:
--        description: 'SSH connection to Actions'
++        description: 'SSH 连接 Actions'
          required: false
          default: false
          type: boolean
++      UPLOAD_RELEASE:
++        description: '上传到发布页面'
++        required: false
++        default: false
++        type: boolean

---

env:
  UPLOAD_FIRMWARE: true
--  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

---

    - name: Generate release tag
      id: tag
--      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
++      if: ${{ inputs.UPLOAD_RELEASE }} && !cancelled()
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        touch release.txt
        echo "::set-output name=status::success"

---

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
--      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
++      if: ${{ inputs.UPLOAD_RELEASE }} && !cancelled()
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
```

大佬能不能在制作镜像的同时 加上 imagebuild 这样就不用 二次编译了，直接加插件就好了

我是弃坑了，太垃圾了

**Comment by wekingchen** [comment]
感谢帮忙优化啦，我也只是在别人基础上改的脚本，复杂了就不会搞呀
这个路由器时不时断流，也是用得很郁闷~

**Comment by Ran-Xing** [comment]
@wekingchen 你咋不用这个固件啊 https://www.right.com.cn/forum/thread-7348817-1-1.html

**20220127** 更新
更新源码
修复几处bug
移除网件主题
移除pas2wall的chandns-ng
新增upnp
新增s2r-plus

**Comment by Ran-Xing** [comment]
我现在又开始郁闷了，拿他当 随身WiFi，AP 用不了，就很难受

**Comment by Ran-Xing** [comment]
你能不能共享一下你的这个配置，我这啥也没有

src/gz openwrt_core http://mirrors.tencent.com/lede//18.06/siflower/sf19a28-fullmask/packages/targets/siflower/sf19a28-fullmask/packages
src/gz openwrt_base http://mirrors.tencent.com/lede//18.06/siflower/sf19a28-fullmask/packages/packages/mips_siflower/base
src/gz openwrt_luci http://mirrors.tencent.com/lede//18.06/siflower/sf19a28-fullmask/packages/packages/mips_siflower/luci
src/gz openwrt_packages http://mirrors.tencent.com/lede//18.06/siflower/sf19a28-fullmask/packages/packages/mips_siflower/packages
src/gz openwrt_passwall http://mirrors.tencent.com/lede//18.06/siflower/sf19a28-fullmask/packages/packages/mips_siflower/passwall
src/gz openwrt_routing http://mirrors.tencent.com/lede//18.06/siflower/sf19a28-fullmask/packages/packages/mips_siflower/routing
src/gz openwrt_telephony http://mirrors.tencent.com/lede//18.06/siflower/sf19a28-fullmask/packages/packages/mips_siflower/telephony

**Comment by wekingchen** [comment]
> 

我就是用这个大佬之前放出来的代码改的，主要是自己编译可以一直更新，他的都一年没动过了，插件版本都旧了

**Comment by wekingchen** [comment]
https://github.com/wekingchen/Actions-SFT1200-OpenWrt/suites/11334112826/artifacts/582535941

这个吗？每次Actions跑完下面都有的哇

**Comment by Ran-Xing** [comment]
@wekingchen 为啥zheshifandian 的信号很好啊，而你的信号很差，你不觉得吗?

**Comment by Ran-Xing** [comment]
有么有啥好用的订阅，用老版本信号强，但是很多插件都安装不了，难受

**Comment by wekingchen** [comment]
没找到啊，资源太少了

**Comment by Ran-Xing** [comment]
你就是全网的希望啊 @wekingchen

**Comment by Ran-Xing** [comment]
对了，你把这个加上吧，官方的，也有不少插件，默认的那个源根本无法访问


```
src/gz glinet_packages https://fw.gl-inet.com/releases/v18.06.5/packages-3.6/siflower/packages
src/gz glinet_private https://fw.gl-inet.com/releases/v18.06.5/packages-3.6/siflower/glinet
src/gz glinet_kmod https://fw.gl-inet.com/releases/v18.06.5/kmod-3.6/siflower/sf19a28_nand
```

**Comment by wekingchen** [comment]
我用官方最新代码，缝合了一个新版，可以试试看信号有没有改善
https://github.com/201821143044/Actions-SFT1200-OpenWrt/suites/11616789418/artifacts/602808416
